apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-config
  namespace: logging
data:
  config.river: |
    // Discover Kubernetes pods to collect metrics from
    discovery.kubernetes "pods" {
      role = "pod"
    }

    // Scrape metrics from discovered pods and forward to remote write
    prometheus.scrape "default" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [prometheus.remote_write.default.receiver]
    }

    // Send metrics to Prometheus remote_write endpoint (no auth)
    prometheus.remote_write "default" {
      endpoint {
        url = "http://localhost:9009/api/prom/push"
      }
    }
