---
# ---------------------------------------------------
# 1. Namespace (logging)
# ---------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---

# ---------------------------------------------------
# 2. Namespace (test)
# ---------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: test
  annotations:
    argocd.argoproj.io/sync-wave: "0"
