---
# ---------------------------------------------------
# 1. ServiceAccount + RBAC (argocd-manager)
# ---------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-manager
  namespace: test
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: statefulset-manager
  namespace: test
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: statefulset-manager-binding
  namespace: test
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: test
roleRef:
  kind: Role
  name: statefulset-manager
  apiGroup: rbac.authorization.k8s.io
---
# ---------------------------------------------------
# 2. ServiceAccount + RBAC (grafana-agent)
# ---------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-agent-logs-metrics
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
      - nodes
      - nodes/proxy
      - endpoints
      - services
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch

  - nonResourceURLs:
      - /metrics
      - /metrics/cadvisor
      - /metrics/resource
    verbs:
      - get
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent-logs-metrics
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent-logs-metrics
subjects:
  - kind: ServiceAccount
    name: grafana-agent
    namespace: logging

---
# ---------------------------------------------------
# 3. ServiceAccount for Prometheus
# ---------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
# ---------------------------------------------------
# ClusterRole with read-only access to Kubernetes objects
# ---------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-pod-reader
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "endpoints", "services"]
    verbs: ["get", "list", "watch"]
---
# ---------------------------------------------------
# ClusterRoleBinding for Prometheus ServiceAccount
# ---------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-pod-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-pod-reader
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: logging
