
# ---------------------------------------------------
# 1. PersistentVolumeClaim (Grafana-pvc)
# ---------------------------------------------------
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# ---------------------------------------------------
# 2. PersistentVolume (loki-storage-pvc)
# ---------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# ---------------------------------------------------
# 3. PersistentVolume (Mongo)
# ---------------------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/data/mongo
