apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
        - name: flask-cassandra-app
          image: dockerelvis/argocd-app:latest
          ports:
            - containerPort: 5000