apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
        - name: flask-cassandra-app
          image: dockerelvis/argocd-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: CASSANDRA_HOST
              value: "cassandra"   # set this to your Cassandra service hostname
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
