apiVersion: batch/v1
kind: Job
metadata:
  name: delete-mongo-statefulset
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: argocd-manager
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command: ["kubectl", "delete", "statefulset", "mongo", "--cascade=orphan"]
