apiVersion: v1
kind: Service
metadata:
  name: argocd-app
spec:
  selector:
    app: argocd-app
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 5000 # Container port
      nodePort: 30080  # Optional: specify NodePort value (must be between 30000-32767)
  type: NodePort
