apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

configMapGenerator:
  - name: agent-config
    files:
      - config.river
    options:
      disableNameSuffixHash: true
