---
# ---------------------------------------------------
# Grafana PersistentVolumeClaim
# ---------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
# ---------------------------------------------------
# Minio PersistentVolumeClaim
# ---------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: test-stage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard

---
# ---------------------------------------------------
# Prometheus PersistentVolumeClaim
# ---------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard

